#!/usr/bin/env sh

sudo yabai --load-sa

# general config
yabai -m config window_border_width          6
yabai -m config window_border                off

# general space settings
yabai -m config layout bsp
yabai -m config bottom_padding 10
yabai -m config top_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10


# ignore apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Raycaast$" manage=off
yabai -m rule --add app="^Hearthstone$" manage=off
yabai -m rule --add app="^Battle.net$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^PS Remote Play$" manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Find My$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^League of Legends$" manage=off
yabai -m rule --add app="^League of Legends(TM) Client$" manage=off
yabai -m rule --add app="^Riot Client$" manage=off
